### ISSUE TITLE
Two Sum

### ISSUE THREAD

**Issue by Sargam-Agarwal** [DSC-Banasthali-Vidyapith/Code-Crossroad#113]
PROBLEM STATEMENT
Given an array of integers nums and an integer target, return the indices of the two numbers such that they add up to the target.

You may assume that each input would have exactly one solution, and you may not use the same element twice.

You can return the answer in any order.

Input: nums = [2,7,11,15], target = 9
Output: [0,1]
Explanation: Because nums[0] + nums[1] == 9, we return [0, 1].

SOLUTION:
I'd like to provide a well commented C++ code to this problem with the most optimised time and space complexity of O(N). I'd like to add the solution in the 'Array' topic folder.  
Kindly assign this issue to me.

**Comment by Ananyaas** [comment]
You can start working on this issue. All the best!
