### ISSUE TITLE
STOCK SPAN PROBLEM

### ISSUE THREAD

**Issue by pratisth2** [DSC-Banasthali-Vidyapith/Code-Crossroad#115]
Question : The stock span problem is a financial problem where we have a series of n daily price quotes for a stock and we need to calculate span of stock’s price for all n days.
The span Si of the stock’s price on a given day i is defined as the maximum number of consecutive days just before the given day, for which the price of the stock on the current day is less than or equal to its price on the given day.

Language: C++
I will optimize time and space complexity in 0(N).
Please assign this issue to me .
Thank  you.

**Comment by Vanshikagarg17** [comment]
You can start working on this issue. All the best!
