### ISSUE TITLE
To change a Expression from Infix to Postfix

### ISSUE THREAD

**Issue by Vanshikagarg17** [DSC-Banasthali-Vidyapith/Code-Crossroad#133]

**Comment by priyanshiparolia** [comment]
Can I do this question in C ?

**Comment by yashneet-kalra** [comment]
I can take this issue up in C as well as C++. Can you assign me this issue @Vanshikagarg17 ?

**Comment by yashneet-kalra** [comment]
> @priyanshiparolia @Tanisha1721 @yashneet-kalra You all can work on this issue, but make sure you work on different languages as mentioned in Readme.md. All the best guys!

Okay sure! I'm doing it in C as of now @Vanshikagarg17 .

**Comment by priyanshiparolia** [comment]
> > @priyanshiparolia @Tanisha1721 @yashneet-kalra You all can work on this issue, but make sure you work on different languages as mentioned in Readme.md. All the best guys!
> 
> Okay sure! I'm doing it in C as of now @Vanshikagarg17 .

hey @yashneet-kalra  as I already mentioned I'm working with C so kindly work on C++ as you stated earlier

**Comment by priyanshiparolia** [comment]
> @priyanshiparolia @Tanisha1721 @yashneet-kalra You all can work on this issue, but make sure you work on different languages as mentioned in Readme.md. All the best guys!

ok di , So I'm working with C

**Comment by yashneet-kalra** [comment]
> > > @priyanshiparolia @Tanisha1721 @yashneet-kalra You all can work on this issue, but make sure you work on different languages as mentioned in Readme.md. All the best guys!
> > 
> > 
> > Okay sure! I'm doing it in C as of now @Vanshikagarg17 .
> 
> hey @yashneet-kalra as I already mentioned I'm working with C so kindly work on C++ as you stated earlier

No problem @priyanshiparolia . I'll do it in C++ :)
