### ISSUE TITLE
Find subarray with given sum

### ISSUE THREAD

**Issue by Vanshikagarg17** [DSC-Banasthali-Vidyapith/Code-Crossroad#144]

**Comment by SauravRaj8** [comment]
can you please assign this issue to me?

Thanks

**Comment by rishitajain01** [comment]
I want to work on this issue, please assign this to me in cpp.

**Comment by Vanshikagarg17** [comment]
@rishitajain01 @SauravRaj8 @pratisth2  You all can work on this issue, but make sure you work on different languages as mentioned in Readme.md. All the best guys!

**Comment by Pratistha27** [comment]
@rishitajain01  which language?

**Comment by rishitajain01** [comment]
@Pratistha27 I have taken this issue and specified the language before you. Can you please do that in other language...

**Comment by SauravRaj8** [comment]
@Vanshikagarg17, I have already created pr in c++ language. Please review it.

**Comment by RahulJaiswal-18** [comment]
@Ananyaas I see that no one is writing the code in java language. I would like to write the java program to solve this problem. Can you assign this to me?

Thanks and Regards

**Comment by Ananyaas** [comment]
@RahulJaiswal-18 you can work on this issue, all the best!

**Comment by Ananyaas** [comment]
@KamalSinghKhanna please specify the language you would like to provide solution in .

**Comment by shreygupta2101** [comment]
Hey, @Ananyaas can assign this issue to me.

**Comment by shreygupta2101** [comment]
I can solve this in java.

**Comment by taranjotsingh23** [comment]
Hey, can I take up this issue? I'll do it in Java
