### ISSUE TITLE
Solve_the_suduko (backtracking)

### ISSUE THREAD

**Issue by SnehaAgarwal361** [DSC-Banasthali-Vidyapith/Code-Crossroad#77]
I would like to solve this issue using the concept of backtracking and recursion with the time complexity of O(9^(n*n)). For every unassigned index, there are 9 possible options so the time complexity of solving the sudoku will be nearly O(9^(n*n)).
Please assign this issue to me.

**Comment by Vanshikagarg17** [comment]
You can start working on this issue. All the best!
