### ISSUE TITLE
Detect negative weight cycle (Bellman Ford's Algorithm)

### ISSUE THREAD

**Issue by Karnika06** [DSC-Banasthali-Vidyapith/Code-Crossroad#80]
### Aim

- We are given a directed graph. We need to detect whether the graph has a negative cycle or not. A negative cycle is one in which the overall sum of the cycle becomes negative.

### Details

- I will be solving this problem using Bellman Ford's Algorithm.
- Bellman Ford algorithm is a algorithm which help us to find the shortest path from a starting vertex to all other vertices of a weighted graph.

I would like to work on this problem using C++ language.
Please assign this issue to me.

**Comment by Vanshikagarg17** [comment]
You can start working on this issue. All the best!
