### ISSUE TITLE
Lowest Common Ancestor of a Binary Tree

### ISSUE THREAD

**Issue by Karnika06** [DSC-Banasthali-Vidyapith/Code-Crossroad#81]
### Aim

- Given a binary tree, find the lowest common ancestor (LCA) of two given nodes in the tree.

### Details

- “The lowest common ancestor is defined between two nodes p and q as the lowest node in T that has both p and q as descendants (where we allow a node to be a descendant of itself).”

I would very much like to work on this issue.
Its a question from LeetCode June challenge and also often comes in interviews.
I would like to use JAVA language for this problem.
Please assign this issue to me.

**Comment by ayushi-manmohan** [comment]
**Aim:**
To find the lowest common ancestor (LCA) of two given nodes in a binary tree.

**Details**
Recursive Approach - I will be solving it using Recursive approach. I will recursively look for any of the two nodes and return it.
The least common ancestor would then be the node for which both the subtree recursions return a non-NULL node.

I wish to work on this problem in **Java** language.
Please assign this to me.
