### ISSUE TITLE
Rotate Linked List

### ISSUE THREAD

**Issue by sparshiigupta** [DSC-Banasthali-Vidyapith/Code-Crossroad#84]
**Aim** : 
Given the head of a linked list, rotate the linked list to the right by k places.

Input: head = [1,2,3,4,5], k = 2
Output: [4,5,1,2,3]

**Details** :
I would like to provide a C++ solution to this problem.
Please assign this issue to me @Vanshikagarg17

**Comment by Vanshikagarg17** [comment]
You can start working on this issue. All the best!
